services:
  schema-tool:
    image: healthri/fdp-schema-update-tool:1.0
    network_mode: host
    volumes:
      - ${PROPERTIES_LOCATION}:/opt/app/Properties.yaml:ro
    command: ["-h", "${FDP_HOST}", "-u", "${FDP_USER}", "-p", "${FDP_PWD}"]
